import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { ThemeProvider } from "next-themes";
import NextProgress from 'nextjs-toploader';
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
	title: "Abdullah Binsaad",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.className} transition-colors`}>
				<NextProgress color="#fcd34d" speed={500} crawlSpeed={500} />
				<div className="flex min-h-screen flex-col gap-6 antialiased container py-2">
					<ThemeProvider attribute="class">
						<Navbar />
						{children}
					</ThemeProvider>
					<hr className="dark:border-neutral-600/50" />
					<Footer />
				</div>
			</body>
		</html>
	);
}
